name: _
description: _
inputs:
  target:
    required: true
  time_zone:
    required: true
outputs:
  time:
    value: ${{ steps.query_time.outputs.time }}
runs:
  using: composite
  steps:
    - name: query
      id: query_time
      if: ${{ inputs.target == 'time' }}
      shell: pwsh
      run: |
        $timeZone = [TimeZoneInfo]::FindSystemTimeZoneById("${{ inputs.time_zone }}")
        $time = [TimeZoneInfo]::ConvertTimeFromUtc((Get-Date).ToUniversalTime(), $timeZone)
        $timeString = $time.ToString("yy-MM-dd HH:mm:ss zzz")
        Add-Content -Encoding utf8 -Path $env:GITHUB_OUTPUT -Value "time=$($timeString)"
