name: _
description: _
inputs:
  host_platform:
    required: true
  version:
    required: true
runs:
  using: composite
  steps:
    - name: install
      if: ${{ inputs.host_platform == 'linux' }}
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path "${{ github.workspace }}/.local/development/appimagetool"
        Invoke-WebRequest -Uri "https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage" -OutFile "${{ github.workspace }}/.local/development/appimagetool/appimagetool"
        chmod +x "${{ github.workspace }}/.local/development/appimagetool/appimagetool"
        Add-Content -Encoding utf8 -Path $env:GITHUB_PATH -Value "${{ github.workspace }}/.local/development/appimagetool"
    - name: check
      if: ${{ inputs.host_platform == 'linux' }}
      shell: pwsh
      run: |
        appimagetool --version
